---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: "https://localhost:8080"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github:clientId
          clientSecret: $github:clientSecret
