apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd 
  labels:
    component: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    repoURL: https://github.com/levivannoort/cluster-configuration.git
    path: operators/external-secrets
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true