apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pause
  namespace: argocd 
  labels:
    component: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    repoURL: https://github.com/levivannoort/cluster-configuration.git
    path: applications/pause
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: pause
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
