apiVersion: v1
kind: Secret
metadata:
  name: scm-authentication
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  type: git
  project: default
  url: https://github.com/levivannoort/cluster-configuration.git
  githubAppId: <base64_encoded_github_app_id>
  githubAppInstallationId: <base64_encoded_github_app_installation_id>
  githubAppPrivateKey: <base64_encoded_github_app_private_key>
